/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.awt.Font;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author leand
 */
public class MainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MainAdmin
     */
    public MainAdmin() {
        initComponents();
        customertbl.getTableHeader().setFont(new Font("Segoe UI Black", Font.BOLD, 12));
        usertbl.getTableHeader().setFont(new Font("Segoe UI Black", Font.BOLD, 12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        Brand = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Customers = new javax.swing.JButton();
        Orders = new javax.swing.JButton();
        Payments = new javax.swing.JButton();
        Items = new javax.swing.JButton();
        Users = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Blank = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CustomerPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customertbl = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        OrderPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ordertbl = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        PaymentPanel = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        paymenttbl = new javax.swing.JTable();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        ItemPanel = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jButton23 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        itemtbl = new javax.swing.JTable();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        UserPanel = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        usertbl = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(56, 34, 15));

        Brand.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        Brand.setForeground(new java.awt.Color(255, 255, 255));
        Brand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/logo.png"))); // NOI18N
        Brand.setText("TCAF");
        Brand.setIconTextGap(0);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Brand, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(808, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Brand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        jPanel5.setBackground(new java.awt.Color(150, 114, 89));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setText("Admin Controls");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        Customers.setBackground(new java.awt.Color(219, 193, 172));
        Customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/customers.png"))); // NOI18N
        Customers.setText("Customers");
        Customers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Customers.setBorderPainted(false);
        Customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomersActionPerformed(evt);
            }
        });
        jPanel5.add(Customers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 140, 40));

        Orders.setBackground(new java.awt.Color(219, 193, 172));
        Orders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/orders.png"))); // NOI18N
        Orders.setText("Orders");
        Orders.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Orders.setBorderPainted(false);
        Orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersActionPerformed(evt);
            }
        });
        jPanel5.add(Orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 140, 40));

        Payments.setBackground(new java.awt.Color(219, 193, 172));
        Payments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/payments.png"))); // NOI18N
        Payments.setText("Payments");
        Payments.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Payments.setBorderPainted(false);
        Payments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentsActionPerformed(evt);
            }
        });
        jPanel5.add(Payments, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 140, 40));

        Items.setBackground(new java.awt.Color(219, 193, 172));
        Items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/items.png"))); // NOI18N
        Items.setText("Items");
        Items.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Items.setBorderPainted(false);
        Items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsActionPerformed(evt);
            }
        });
        jPanel5.add(Items, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 140, 40));

        Users.setBackground(new java.awt.Color(219, 193, 172));
        Users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/accnt.png"))); // NOI18N
        Users.setText("Accounts");
        Users.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Users.setBorderPainted(false);
        Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersActionPerformed(evt);
            }
        });
        jPanel5.add(Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 140, 40));

        Logout.setBackground(new java.awt.Color(219, 193, 172));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/out.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Logout.setBorderPainted(false);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel5.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 120, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 490));

        Blank.setBackground(new java.awt.Color(219, 193, 172));
        Blank.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("WELCOME");
        Blank.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 225, -1, -1));

        jTabbedPane1.addTab("Welcome", Blank);

        CustomerPanel.setBackground(new java.awt.Color(219, 193, 172));
        CustomerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Customer ID", "Customer Name", "Contact Info"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(customertbl);

        CustomerPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 147, 610, 340));
        CustomerPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 49, 140, 30));

        jLabel2.setText("ID:");
        CustomerPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 29, -1, -1));

        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        CustomerPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jButton8.setText("Update");
        CustomerPanel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 30));

        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        CustomerPanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 30));
        CustomerPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 49, 138, 30));

        jButton10.setText("Search");
        CustomerPanel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 30));

        jLabel3.setText("Name:");
        CustomerPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 29, -1, -1));

        jLabel4.setText("Contact Info:");
        CustomerPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 29, -1, -1));
        CustomerPanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 49, 138, 30));

        jTabbedPane1.addTab("Customer", CustomerPanel);

        OrderPanel.setBackground(new java.awt.Color(219, 193, 172));
        OrderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ordertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer ID", "Order Date", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(ordertbl);

        OrderPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 147, 610, 340));
        OrderPanel.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 49, 140, 30));

        jLabel6.setText("ID:");
        OrderPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 29, -1, -1));

        jButton6.setText("Insert");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        OrderPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jButton11.setText("Update");
        OrderPanel.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 30));

        jButton12.setText("Delete");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        OrderPanel.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 30));
        OrderPanel.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 49, 138, 30));

        jButton13.setText("Search");
        OrderPanel.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 30));

        jLabel7.setText("Name:");
        OrderPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 29, -1, -1));

        jLabel11.setText("Contact Info:");
        OrderPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 29, -1, -1));
        OrderPanel.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 49, 138, 30));

        jTabbedPane1.addTab("Order", OrderPanel);

        PaymentPanel.setBackground(new java.awt.Color(219, 193, 172));
        PaymentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setText("Delete");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        PaymentPanel.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 30));
        PaymentPanel.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 49, 138, 30));

        jButton19.setText("Search");
        PaymentPanel.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 30));

        jLabel12.setText("Name:");
        PaymentPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 29, -1, -1));

        jLabel13.setText("Contact Info:");
        PaymentPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 29, -1, -1));

        paymenttbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PaymentID", "OrderID", "Amount", "Payment Method"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(paymenttbl);

        PaymentPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 147, 610, 340));
        PaymentPanel.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 49, 138, 30));
        PaymentPanel.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 49, 140, 30));

        jLabel14.setText("ID:");
        PaymentPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 29, -1, -1));

        jButton20.setText("Insert");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        PaymentPanel.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jButton21.setText("Update");
        PaymentPanel.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 30));

        jTabbedPane1.addTab("Payment", PaymentPanel);

        ItemPanel.setBackground(new java.awt.Color(219, 193, 172));
        ItemPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton22.setText("Delete");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        ItemPanel.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 30));
        ItemPanel.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 49, 138, 30));

        jButton23.setText("Search");
        ItemPanel.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 30));

        jLabel15.setText("Name:");
        ItemPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 29, -1, -1));

        jLabel16.setText("Contact Info:");
        ItemPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 29, -1, -1));

        itemtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer ID", "Order Date", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(itemtbl);

        ItemPanel.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 147, 610, 340));
        ItemPanel.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 49, 138, 30));
        ItemPanel.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 49, 140, 30));

        jLabel17.setText("ID:");
        ItemPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 29, -1, -1));

        jButton24.setText("Insert");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        ItemPanel.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jButton25.setText("Update");
        ItemPanel.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 30));

        jTabbedPane1.addTab("Items", ItemPanel);

        UserPanel.setBackground(new java.awt.Color(219, 193, 172));
        UserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        UserPanel.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 49, 140, 30));

        jLabel8.setText("ID:");
        UserPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 29, -1, -1));
        UserPanel.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 49, 138, 30));

        jLabel9.setText("Name:");
        UserPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 29, -1, -1));

        jLabel10.setText("Contact Info:");
        UserPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 29, -1, -1));
        UserPanel.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 49, 138, 30));

        jButton15.setText("Insert");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        UserPanel.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        usertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Email", "Password", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(usertbl);

        UserPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 147, 610, 340));

        jButton16.setText("Update");
        UserPanel.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 30));

        jButton17.setText("Delete");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        UserPanel.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 30));

        jButton18.setText("Search");
        UserPanel.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 30));

        jTabbedPane1.addTab("Accounts", UserPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 670, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Confirm Logout");
        if (a == 0){
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5); 
        usertbl.getColumnModel().getColumn(0).setPreferredWidth(50);
        usertbl.getColumnModel().getColumn(1).setPreferredWidth(100);
        usertbl.getColumnModel().getColumn(2).setPreferredWidth(200);
        usertbl.getColumnModel().getColumn(3).setPreferredWidth(150);
        usertbl.getColumnModel().getColumn(4).setPreferredWidth(100);
        
        try {
            Statement st = dbcon.dbconnect().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM users");
            
            DefaultTableModel model = (DefaultTableModel)usertbl.getModel();
            
            model.setRowCount(0);
            
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }
            
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(MainAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UsersActionPerformed

    private void ItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsActionPerformed
        jTabbedPane1.setSelectedIndex(4);
        try {
            Statement st = dbcon.dbconnect().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM items");
            
            DefaultTableModel model = (DefaultTableModel)paymenttbl.getModel();
            
            model.setRowCount(0);
            
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(MainAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ItemsActionPerformed

    private void PaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentsActionPerformed
        jTabbedPane1.setSelectedIndex(3);
        try {
            Statement st = dbcon.dbconnect().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM payments");
            
            DefaultTableModel model = (DefaultTableModel)paymenttbl.getModel();
            
            model.setRowCount(0);
            
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(MainAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PaymentsActionPerformed

    private void OrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        try {
            Statement st = dbcon.dbconnect().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM orders");
            
            DefaultTableModel model = (DefaultTableModel)ordertbl.getModel();
            
            model.setRowCount(0);
            
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
            
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(MainAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OrdersActionPerformed

    private void CustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomersActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        try {
            Statement st = dbcon.dbconnect().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM customers");
            
            DefaultTableModel model = (DefaultTableModel)customertbl.getModel();
            
            model.setRowCount(0);
            
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3)});
            }
            
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(MainAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CustomersActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    /**
     * @param args the command line arguments
    */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Blank;
    private javax.swing.JLabel Brand;
    private javax.swing.JPanel CustomerPanel;
    private javax.swing.JButton Customers;
    private javax.swing.JPanel ItemPanel;
    private javax.swing.JButton Items;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel OrderPanel;
    private javax.swing.JButton Orders;
    private javax.swing.JPanel PaymentPanel;
    private javax.swing.JButton Payments;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JButton Users;
    private javax.swing.JTable customertbl;
    private javax.swing.JTable itemtbl;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable ordertbl;
    private javax.swing.JTable paymenttbl;
    private javax.swing.JTable usertbl;
    // End of variables declaration//GEN-END:variables
}
