/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.awt.Font;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author leand
 */
public class MainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MainAdmin
     */
    public MainAdmin() {
        initComponents();
        customertbl.getTableHeader().setFont(new Font("Segoe UI Black", Font.BOLD, 12));
        usertbl.getTableHeader().setFont(new Font("Segoe UI Black", Font.BOLD, 12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        Brand = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Customers = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Users = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Blank = new javax.swing.JPanel();
        CustomerPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customertbl = new javax.swing.JTable();
        CustIdBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InsertButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        NameBox = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ConInfoBox = new javax.swing.JTextField();
        Blank1 = new javax.swing.JPanel();
        Blank2 = new javax.swing.JPanel();
        Blank3 = new javax.swing.JPanel();
        UserPanel = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        usertbl = new javax.swing.JTable();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(56, 34, 15));

        Brand.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        Brand.setForeground(new java.awt.Color(255, 255, 255));
        Brand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/logo.png"))); // NOI18N
        Brand.setText("TCAF");
        Brand.setIconTextGap(0);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Brand, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(808, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Brand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        jPanel5.setBackground(new java.awt.Color(150, 114, 89));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setText("Admin Controls");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        Customers.setBackground(new java.awt.Color(219, 193, 172));
        Customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/customers.png"))); // NOI18N
        Customers.setText("Customers");
        Customers.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Customers.setBorderPainted(false);
        Customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomersActionPerformed(evt);
            }
        });
        jPanel5.add(Customers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 140, 40));

        jButton3.setBackground(new java.awt.Color(219, 193, 172));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/orders.png"))); // NOI18N
        jButton3.setText("Orders");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 140, 40));

        jButton4.setBackground(new java.awt.Color(219, 193, 172));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/payments.png"))); // NOI18N
        jButton4.setText("Payments");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 140, 40));

        jButton5.setBackground(new java.awt.Color(219, 193, 172));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/items.png"))); // NOI18N
        jButton5.setText("Items");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 140, 40));

        Users.setBackground(new java.awt.Color(219, 193, 172));
        Users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/accnt.png"))); // NOI18N
        Users.setText("Accounts");
        Users.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Users.setBorderPainted(false);
        Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersActionPerformed(evt);
            }
        });
        jPanel5.add(Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 140, 40));

        jButton7.setBackground(new java.awt.Color(219, 193, 172));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/out.png"))); // NOI18N
        jButton7.setText("Logout");
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 120, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 490));

        Blank.setBackground(new java.awt.Color(219, 193, 172));

        javax.swing.GroupLayout BlankLayout = new javax.swing.GroupLayout(Blank);
        Blank.setLayout(BlankLayout);
        BlankLayout.setHorizontalGroup(
            BlankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        BlankLayout.setVerticalGroup(
            BlankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", Blank);

        CustomerPanel.setBackground(new java.awt.Color(219, 193, 172));
        CustomerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Customer ID", "Customer Name", "Contact Info"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(customertbl);

        CustomerPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 147, 610, 340));
        CustomerPanel.add(CustIdBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 49, 140, 30));

        jLabel2.setText("ID:");
        CustomerPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 29, -1, -1));

        InsertButton.setText("Insert");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertButtonActionPerformed(evt);
            }
        });
        CustomerPanel.add(InsertButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        UpdateButton.setText("Update");
        CustomerPanel.add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 30));

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        CustomerPanel.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 30));
        CustomerPanel.add(NameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 49, 138, 30));

        SearchButton.setText("Search");
        CustomerPanel.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 30));

        jLabel3.setText("Name:");
        CustomerPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 29, -1, -1));

        jLabel4.setText("Contact Info:");
        CustomerPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 29, -1, -1));
        CustomerPanel.add(ConInfoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 49, 138, 30));

        jTabbedPane1.addTab("tab1", CustomerPanel);

        Blank1.setBackground(new java.awt.Color(219, 193, 172));

        javax.swing.GroupLayout Blank1Layout = new javax.swing.GroupLayout(Blank1);
        Blank1.setLayout(Blank1Layout);
        Blank1Layout.setHorizontalGroup(
            Blank1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        Blank1Layout.setVerticalGroup(
            Blank1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", Blank1);

        Blank2.setBackground(new java.awt.Color(219, 193, 172));

        javax.swing.GroupLayout Blank2Layout = new javax.swing.GroupLayout(Blank2);
        Blank2.setLayout(Blank2Layout);
        Blank2Layout.setHorizontalGroup(
            Blank2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        Blank2Layout.setVerticalGroup(
            Blank2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", Blank2);

        Blank3.setBackground(new java.awt.Color(219, 193, 172));

        javax.swing.GroupLayout Blank3Layout = new javax.swing.GroupLayout(Blank3);
        Blank3.setLayout(Blank3Layout);
        Blank3Layout.setHorizontalGroup(
            Blank3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        Blank3Layout.setVerticalGroup(
            Blank3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", Blank3);

        UserPanel.setBackground(new java.awt.Color(219, 193, 172));
        UserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        UserPanel.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 49, 140, 30));

        jLabel8.setText("ID:");
        UserPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 29, -1, -1));
        UserPanel.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 49, 138, 30));

        jLabel9.setText("Name:");
        UserPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 29, -1, -1));

        jLabel10.setText("Contact Info:");
        UserPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 29, -1, -1));
        UserPanel.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 49, 138, 30));

        jButton15.setText("Insert");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        UserPanel.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        usertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Email", "Password", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(usertbl);

        UserPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 147, 610, 340));

        jButton16.setText("Update");
        UserPanel.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 30));

        jButton17.setText("Delete");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        UserPanel.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 30));

        jButton18.setText("Search");
        UserPanel.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 30));

        jTabbedPane1.addTab("tab2", UserPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 670, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Confirm Logout");
        if (a == 0){
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5); 
        usertbl.getColumnModel().getColumn(0).setPreferredWidth(50);
        usertbl.getColumnModel().getColumn(1).setPreferredWidth(100);
        usertbl.getColumnModel().getColumn(2).setPreferredWidth(200);
        usertbl.getColumnModel().getColumn(3).setPreferredWidth(150);
        usertbl.getColumnModel().getColumn(4).setPreferredWidth(100);
        
        try {
            Statement st = dbcon.dbconnect().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM users");
            
            DefaultTableModel model = (DefaultTableModel)usertbl.getModel();
            
            model.setRowCount(0);
            
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }
            
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(MainAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UsersActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomersActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        try {
            Statement st = dbcon.dbconnect().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM customers");
            
            DefaultTableModel model = (DefaultTableModel)customertbl.getModel();
            
            model.setRowCount(0);
            
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3)});
            }
            
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(MainAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CustomersActionPerformed

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        // TODO add your handling code here:
        String CustId = CustIdBox.getText();
        String Name = NameBox.getText();
        String ConInfo = ConInfoBox.getText();
        if (CustId.isEmpty()) {
            JOptionPane.showMessageDialog(null, "CustomerID is REQUIRED");
        } else if (Name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Name is REQUIRED");
        } else if (ConInfo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Contact Info is REQUIRED");
        } else {
            
            
            // Use the existing connection
            try (Connection connect = dbcon.dbconnect();
                 Statement stmt = connect.createStatement()) {

                String customer = "INSERT INTO customer (CustomerID, Name, ContactInfo) " +
                        "VALUES (" + CustId + ", '" + Name + "', '" + ConInfo + "')";
                
               
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error adding equipment: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_InsertButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
    */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Blank;
    private javax.swing.JPanel Blank1;
    private javax.swing.JPanel Blank2;
    private javax.swing.JPanel Blank3;
    private javax.swing.JLabel Brand;
    private javax.swing.JTextField ConInfoBox;
    private javax.swing.JTextField CustIdBox;
    private javax.swing.JPanel CustomerPanel;
    private javax.swing.JButton Customers;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton InsertButton;
    private javax.swing.JTextField NameBox;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JButton Users;
    private javax.swing.JTable customertbl;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable usertbl;
    // End of variables declaration//GEN-END:variables
}
