package Main;

import java.sql.PreparedStatement;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


public class MainStaff extends javax.swing.JFrame {

    public MainStaff() {
        initComponents();
        loadData();
        
        coffeeTbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                int row = coffeeTbl.getSelectedRow();
                if (row >= 0) {
                    itemname.setText(coffeeTbl.getValueAt(row, 1).toString()); 
                }
            }
        });

        teaTbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                int row = teaTbl.getSelectedRow();
                if (row >= 0) {
                    itemname.setText(teaTbl.getValueAt(row, 1).toString()); 
                }
            }
        });

        pastTbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                int row = pastTbl.getSelectedRow();
                if (row >= 0) {
                    itemname.setText(pastTbl.getValueAt(row, 1).toString());
                }
            }
        });
        
        orderTbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                int row = orderTbl.getSelectedRow();
                if (row >= 0) {
                    String name = orderTbl.getValueAt(row, 1).toString(); 
                    int quantity = (Integer) orderTbl.getValueAt(row, 3); 

                    itemname.setText(name); 
                    odqty.setValue(quantity);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        coffeeTbl = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        teaTbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        pastTbl = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        paymethod = new javax.swing.JComboBox<>();
        print = new javax.swing.JButton();
        pay = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ccontactinfo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTbl = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        Edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        itemname = new javax.swing.JTextField();
        odqty = new javax.swing.JSpinner();
        addOrder = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        pays = new javax.swing.JTextField();
        change = new javax.swing.JLabel();
        three = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        five = new javax.swing.JButton();
        four = new javax.swing.JButton();
        six = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        del = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        Brand = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, null));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        coffeeTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Description", "Price", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(coffeeTbl);

        jPanel1.add(jScrollPane3);

        jTabbedPane1.addTab("Coffee", jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        teaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Description", "Price", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(teaTbl);

        jPanel2.add(jScrollPane4);

        jTabbedPane1.addTab("Tea", jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        pastTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Description", "Price", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(pastTbl);

        jPanel3.add(jScrollPane5);

        jTabbedPane1.addTab("Pastries", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 515, 456));

        paymethod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paymethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Check", "Credit" }));
        paymethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymethodActionPerformed(evt);
            }
        });

        print.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        pay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pay.setText("PAY");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("PAYMENT METHOD :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Customer Name :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Contact Info :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(paymethod, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccontactinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(paymethod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ccontactinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 630, -1, -1));

        orderTbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, null));
        orderTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Price", "Quantity", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(orderTbl);
        if (orderTbl.getColumnModel().getColumnCount() > 0) {
            orderTbl.getColumnModel().getColumn(0).setResizable(false);
            orderTbl.getColumnModel().getColumn(1).setResizable(false);
            orderTbl.getColumnModel().getColumn(2).setResizable(false);
            orderTbl.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 461, 456));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Edit.setText("EDIT");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel5.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 80, -1));

        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel5.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Item Name :");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 26));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Quantity :");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 26));
        jPanel5.add(itemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 133, 26));
        jPanel5.add(odqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 130, 30));

        addOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addOrder.setText("ADD");
        addOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderActionPerformed(evt);
            }
        });
        jPanel5.add(addOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 80, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 460, 110));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("TOTAL :");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("PAY :");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 24));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("CHANGE:");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("0");
        jPanel6.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 130, -1));

        pays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paysActionPerformed(evt);
            }
        });
        jPanel6.add(pays, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 130, 24));

        change.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        change.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        change.setText("0");
        jPanel6.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 130, -1));

        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        jPanel6.add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 50, 50));

        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        jPanel6.add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 50, 50));

        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        jPanel6.add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 50, 50));

        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        jPanel6.add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 50, 50));

        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        jPanel6.add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 50, 50));

        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        jPanel6.add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 50, 50));

        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        jPanel6.add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 50, 50));

        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        jPanel6.add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 50, 50));

        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        jPanel6.add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 50, 50));

        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        jPanel6.add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 50, 50));

        del.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        del.setText("Del");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel6.add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 50, 50));

        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel6.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 50, 50));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 453, 256));

        Brand.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        Brand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/logo.png"))); // NOI18N
        Brand.setText("TCAF");
        Brand.setIconTextGap(0);
        getContentPane().add(Brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 8)); // NOI18N
        jLabel7.setText("Tea and Coffee Shop");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paysActionPerformed

    private void paymethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymethodActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        String customerName = cname.getText().trim();
        String contactInfo = ccontactinfo.getText().trim();

        if (customerName.isEmpty() || contactInfo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter customer name and contact info.");
            return;
        }

        double totalPrice = Double.parseDouble(total.getText());
        double paymentAmount = 0.0;

        try {
            paymentAmount = Double.parseDouble(pays.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid payment amount.");
            return;
        }

        if (paymentAmount < totalPrice) {
            JOptionPane.showMessageDialog(this, String.format("Insufficient payment. Total: %.2f, Paid: %.2f.", totalPrice, paymentAmount));
            return;
        }

        Connection conn = dbcon.dbconnect();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Database connection failed.");
            return;
        }

        String paymentMethod = paymethod.getSelectedItem().toString();
        String paymentStatus = paymentAmount == totalPrice ? "Paid" : "Unpaid";

        try {
            conn.setAutoCommit(false);

            String insertCustomerSql = "INSERT INTO customers (Name, ContactInfo) VALUES (?, ?)";
            try (PreparedStatement pstmt = conn.prepareStatement(insertCustomerSql, Statement.RETURN_GENERATED_KEYS)) {
                pstmt.setString(1, customerName);
                pstmt.setString(2, contactInfo);
                pstmt.executeUpdate();

                ResultSet generatedKeys = pstmt.getGeneratedKeys();
                if (!generatedKeys.next()) {
                    throw new SQLException("Creating customer failed, no ID obtained.");
                }
                int customerId = generatedKeys.getInt(1);

                String insertOrderSql = "INSERT INTO orders (CustomerID, OrderDate, TotalAmount) VALUES (?, CURDATE(), ?)";
                try (PreparedStatement orderPstmt = conn.prepareStatement(insertOrderSql, Statement.RETURN_GENERATED_KEYS)) {
                    orderPstmt.setInt(1, customerId);
                    orderPstmt.setDouble(2, totalPrice);
                    orderPstmt.executeUpdate();

                    ResultSet orderKeys = orderPstmt.getGeneratedKeys();
                    if (!orderKeys.next()) {
                        throw new SQLException("Creating order failed, no ID obtained.");
                    }
                    int orderId = orderKeys.getInt(1);

                    DefaultTableModel orderTableModel = (DefaultTableModel) orderTbl.getModel();
                    for (int i = 0; i < orderTableModel.getRowCount(); i++) {
                        String itemId = (String) orderTableModel.getValueAt(i, 0);
                        int quantity = (Integer) orderTableModel.getValueAt(i, 3);

                        String insertOrderDetailSql = "INSERT INTO orderdetails (OrderID, ItemID, Quantity) VALUES (?, ?, ?)";
                        try (PreparedStatement orderDetailPstmt = conn.prepareStatement(insertOrderDetailSql)) {
                            orderDetailPstmt.setInt(1, orderId);
                            orderDetailPstmt.setInt(2, Integer.parseInt(itemId));
                            orderDetailPstmt.setInt(3, quantity);
                            orderDetailPstmt.executeUpdate();
                        }

                        String updateStockSql = "UPDATE items SET Stock = Stock - ? WHERE ItemID = ?";
                        try (PreparedStatement updateStockPstmt = conn.prepareStatement(updateStockSql)) {
                            updateStockPstmt.setInt(1, quantity);
                            updateStockPstmt.setInt(2, Integer.parseInt(itemId));
                            updateStockPstmt.executeUpdate();
                        }
                    }

                    String insertPaymentSql = "INSERT INTO payments (OrderID, Amount, PaymentMethod, Status) VALUES (?, ?, ?, ?)";
                    try (PreparedStatement paymentPstmt = conn.prepareStatement(insertPaymentSql)) {
                        paymentPstmt.setInt(1, orderId);
                        paymentPstmt.setDouble(2, paymentAmount);
                        paymentPstmt.setString(3, paymentMethod);
                        paymentPstmt.setString(4, paymentStatus);
                        paymentPstmt.executeUpdate();
                    }

                    if ("Card".equals(paymentMethod)) {
                        String cardDetails = getCardDetailsFromUser();
                        JOptionPane.showMessageDialog(this, "Payment via Card successful!\nCard Details: " + cardDetails);
                    } else if ("Check".equals(paymentMethod)) {
                        String checkNumber = getCheckNumberFromUser();
                        JOptionPane.showMessageDialog(this, "Payment via Check successful!\nCheck Number: " + checkNumber);
                    }

                    conn.commit();
                    JOptionPane.showMessageDialog(this, "Payment successful!");

                    orderTableModel.setRowCount(0);
                    cname.setText("");
                    ccontactinfo.setText("");
                    pays.setText("");
                    total.setText("0");
                    loadData();
                }
            }
        } catch (SQLException e) {
            try {
                conn.rollback();
            } catch (SQLException rollbackEx) {
                JOptionPane.showMessageDialog(this, "Error during transaction rollback: " + rollbackEx.getMessage());
            }
            JOptionPane.showMessageDialog(this, e.getMessage());
        } finally {
            try {
                conn.setAutoCommit(true);
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error closing connection: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_payActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int selectedRow = orderTbl.getSelectedRow(); 

        if (selectedRow == -1) {

            JOptionPane.showMessageDialog(this, "Please select an order to delete.");
            return;
        }

        
            DefaultTableModel model = (DefaultTableModel) orderTbl.getModel(); 
            model.removeRow(selectedRow); 

    }//GEN-LAST:event_deleteActionPerformed

    private void addOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderActionPerformed
        String name = itemname.getText();
        int quantity = (Integer) odqty.getValue(); 

        if (name.isEmpty() || quantity <= 0) {
            JOptionPane.showMessageDialog(this, "Please select an item and enter a valid quantity.");
            return;
        }

        double price = 0.0;
        String itemId = ""; 
        int availableStock = 0; 
        try {
            String sql = "SELECT ItemID, Price, Stock FROM items WHERE ItemName = ?";
            Connection conn = dbcon.dbconnect();
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, name);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                itemId = rs.getString("ItemID"); 
                price = rs.getDouble("Price"); 
                availableStock = rs.getInt("Stock"); 
            } else {
                JOptionPane.showMessageDialog(this, "Item not found.");
                return;
            }

            if (quantity > availableStock) {
                JOptionPane.showMessageDialog(this, "Requested quantity exceeds available stock. \nAvailable stock: " + availableStock);
                return;
            }

            DefaultTableModel orderTableModel = (DefaultTableModel) orderTbl.getModel();
            boolean itemExists = false;

            for (int i = 0; i < orderTableModel.getRowCount(); i++) {
                if (orderTableModel.getValueAt(i, 1).equals(name)) { 
                    int existingQuantity = (Integer) orderTableModel.getValueAt(i, 3); 
                    existingQuantity += quantity; 

                    if (existingQuantity > availableStock) {
                        JOptionPane.showMessageDialog(this, "Total quantity exceeds available stock after addition. Available stock: " + availableStock);
                        return;
                    }

                    orderTableModel.setValueAt(existingQuantity, i, 3);

                    double newSubtotal = price * existingQuantity;
                    orderTableModel.setValueAt(newSubtotal, i, 4); 
                    itemExists = true;
                    break;
                }
            }

            if (!itemExists) {
                double subtotal = price * quantity;
                orderTableModel.addRow(new Object[]{itemId, name, price, quantity, subtotal});  
            }

            itemname.setText(""); 
            odqty.setValue(1);
            calculateTotal();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error adding item to order: " + e.getMessage());
        }
    }//GEN-LAST:event_addOrderActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        pays.setText(pays.getText() + "3");
        calculateChange();
    }//GEN-LAST:event_threeActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        pays.setText(pays.getText() + "1");
        calculateChange();
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        pays.setText(pays.getText() + "2");
        calculateChange();
    }//GEN-LAST:event_twoActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        pays.setText(pays.getText() + "5");
        calculateChange();
    }//GEN-LAST:event_fiveActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        pays.setText(pays.getText() + "4");
        calculateChange();
    }//GEN-LAST:event_fourActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        pays.setText(pays.getText() + "6");
        calculateChange();
    }//GEN-LAST:event_sixActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        pays.setText(pays.getText() + "8");
        calculateChange();
    }//GEN-LAST:event_eightActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        pays.setText(pays.getText() + "7");
        calculateChange();
    }//GEN-LAST:event_sevenActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        pays.setText(pays.getText() + "9");
        calculateChange();
    }//GEN-LAST:event_nineActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        pays.setText(pays.getText() + "0");
        calculateChange();
    }//GEN-LAST:event_zeroActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        String currentText = pays.getText();
        if (!currentText.isEmpty()) {
            pays.setText(currentText.substring(0, currentText.length() - 1));
        }
        calculateChange();
    }//GEN-LAST:event_delActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        pays.setText("");
        calculateChange();
    }//GEN-LAST:event_clearActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        int selectedRow = orderTbl.getSelectedRow(); 

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an order to edit.");
            return;
        }

        String name = itemname.getText(); 
        int newQuantity = (Integer) odqty.getValue(); 

        if (newQuantity <= 0) {
            JOptionPane.showMessageDialog(this, "Please enter a valid quantity.");
            return;
        }

        double price = (Double) orderTbl.getValueAt(selectedRow, 2); 
        String itemId = (String) orderTbl.getValueAt(selectedRow, 0); 

        int availableStock = 0;

        try {
            String sql = "SELECT Stock FROM items WHERE ItemID = ?";
            Connection conn = dbcon.dbconnect();
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, itemId);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                availableStock = rs.getInt("Stock"); 
            } else {
                JOptionPane.showMessageDialog(this, "Item not found.");
                return;
            }

            if (newQuantity > availableStock) {
                JOptionPane.showMessageDialog(this, "Requested quantity exceeds available stock. Available stock: " + availableStock);
                return;
            }

            orderTbl.setValueAt(newQuantity, selectedRow, 3);

            double newSubtotal = price * newQuantity; 
            orderTbl.setValueAt(newSubtotal, selectedRow, 4);

            itemname.setText(""); 
            odqty.setValue(1); 
            calculateTotal();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error fetching stock information: " + e.getMessage());
        }
    }//GEN-LAST:event_EditActionPerformed

    private void loadData() {
        loadItemsByCategory("Coffee", coffeeTbl);
        loadItemsByCategory("Tea", teaTbl);
        loadItemsByCategory("Pastries", pastTbl);
    }

    private void loadItemsByCategory(String category, JTable table) {
        Connection conn = dbcon.dbconnect();
        if (conn == null) return;

        try {
            String sql = "SELECT * FROM items WHERE Category = ?"; 
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, category);
            ResultSet rs = pstmt.executeQuery();

            DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
            tableModel.setRowCount(0); 

            while (rs.next()) {
                String itemID = rs.getString("ItemID");
                String itemName = rs.getString("ItemName");
                String description = rs.getString("Description");
                double price = rs.getDouble("Price");
                int stock = rs.getInt("Stock");

                tableModel.addRow(new Object[]{itemID, itemName, description, price, stock});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading " + category + " data: " + e.getMessage());
        } 
    }
    
    private void calculateTotal() {
        double totalValue = 0.0;
        DefaultTableModel model = (DefaultTableModel) orderTbl.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            totalValue += (double) model.getValueAt(i, 4);
        }
        total.setText(String.format("%.2f", totalValue));
    }
    
    private void calculateChange() {
        double totalValue = Double.parseDouble(total.getText());
        String payAmountText = pays.getText();

        try {
            double payAmount = payAmountText.isEmpty() ? 0 : Double.parseDouble(payAmountText);

            if (payAmount >= totalValue) {
                double changeValue = payAmount - totalValue;
                change.setText(String.format("%.2f", changeValue)); 
            } else {
                change.setText("0.00"); 
            }
        } catch (NumberFormatException e) {
            change.setText("0.00"); 
        }
    }
    
    private String getCardDetailsFromUser() {
        JTextField cardNumberField = new JTextField();
        JTextField expirationDateField = new JTextField();
        Object[] message = {
            "Card Number:", cardNumberField,
            "Expiration Date (MM/YY):", expirationDateField
        };

        int option = JOptionPane.showConfirmDialog(null, message, "Enter Card Details", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            return cardNumberField.getText() + "," + expirationDateField.getText(); 
        }
        return null;
    }

    private String getCheckNumberFromUser() {
        String checkNumber = JOptionPane.showInputDialog(this, "Enter the Check Number:");
        return checkNumber != null ? checkNumber : ""; 
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                new MainStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Brand;
    private javax.swing.JButton Edit;
    private javax.swing.JButton addOrder;
    private javax.swing.JTextField ccontactinfo;
    private javax.swing.JLabel change;
    private javax.swing.JButton clear;
    private javax.swing.JTextField cname;
    private javax.swing.JTable coffeeTbl;
    private javax.swing.JButton del;
    private javax.swing.JButton delete;
    private javax.swing.JButton eight;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JTextField itemname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton nine;
    private javax.swing.JSpinner odqty;
    private javax.swing.JButton one;
    private javax.swing.JTable orderTbl;
    private javax.swing.JTable pastTbl;
    private javax.swing.JButton pay;
    private javax.swing.JComboBox<String> paymethod;
    private javax.swing.JTextField pays;
    private javax.swing.JButton print;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JTable teaTbl;
    private javax.swing.JButton three;
    private javax.swing.JLabel total;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
