/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author leand
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namesignup = new javax.swing.JTextField();
        emailsignup = new javax.swing.JTextField();
        passsignup = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        createaccbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        backloginbtn = new javax.swing.JButton();
        status = new javax.swing.JComboBox<>();
        statusbtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 242, 225));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namesignup.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        namesignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namesignupActionPerformed(evt);
            }
        });
        jPanel1.add(namesignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 103, 241, 31));

        emailsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailsignupActionPerformed(evt);
            }
        });
        jPanel1.add(emailsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 163, 241, 34));

        passsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passsignupActionPerformed(evt);
            }
        });
        jPanel1.add(passsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 232, 241, 34));

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel2.setText("Username:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 80, 85, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 140, 57, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 209, 71, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel5.setText("Sign Up");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 18, -1, 36));

        createaccbtn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        createaccbtn.setText("Create Account");
        createaccbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaccbtnActionPerformed(evt);
            }
        });
        jPanel1.add(createaccbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLabel6.setText("I have an account");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        backloginbtn.setText("Log In");
        backloginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backloginbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backloginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        status.setSelectedIndex(-1);
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 130, 40));

        statusbtn.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        statusbtn.setText("Status:");
        jPanel1.add(statusbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 420, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/wall2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namesignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namesignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namesignupActionPerformed

    private void emailsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailsignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailsignupActionPerformed

    private void passsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passsignupActionPerformed
        // TODO add your handling code here:
               
    }//GEN-LAST:event_passsignupActionPerformed

    private void createaccbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaccbtnActionPerformed
        // TODO add your handling code here:
        String usernameSignup, passwordSignup, emailSignup, statusSignup, userDB = null, emailDB = null, passDB = null, statusDB = null;
        boolean found = false;
        
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tcsss_oop","root", "");
            Statement st = con.createStatement();
            
            if(namesignup.getText().equals("")){
                JOptionPane.showMessageDialog(new JFrame(), "Username is required", "Error!", JOptionPane.ERROR_MESSAGE);
            } 
            else if (passsignup.getText().equals("")) {
                JOptionPane.showMessageDialog(new JFrame(), "Password is required", "Error!", JOptionPane.ERROR_MESSAGE);
            }
            else if (status.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(new JFrame(), "Status is required", "Error!", JOptionPane.ERROR_MESSAGE);
            }
            else if (emailsignup.getText().equals("")) {
                JOptionPane.showMessageDialog(new JFrame(), "Email is required", "Error!", JOptionPane.ERROR_MESSAGE);
            }
            else {
                usernameSignup    = namesignup.getText();
                passwordSignup = passsignup.getText();  
                
                ResultSet rs = st.executeQuery("SELECT * FROM users WHERE Username = '" + usernameSignup + "'");
                while(rs.next()){
                userDB = rs.getString("Username");
                emailDB = rs.getString("Email");
                passDB = rs.getString("Password");
                statusDB = rs.getString("Status");
                found = true;
                }
                
                if (found && passsignup.equals(passDB) && "Admin".equals(statusDB)){
                        new Admin().setVisible(true);
                        this.dispose();
                    }
                else if (found && passsignup.equals(passDB) && "Staff".equals(statusDB)){
                        new MainStaff().setVisible(true);
                        this.dispose();
                    }
                else {
                    JOptionPane.showMessageDialog(new JFrame(), "Incorrect email or password", "Error!", JOptionPane.ERROR_MESSAGE);
                    passsignup.setText("");
                    }
                    
            }
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_createaccbtnActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void backloginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backloginbtnActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_backloginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backloginbtn;
    private javax.swing.JButton createaccbtn;
    private javax.swing.JTextField emailsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField namesignup;
    private javax.swing.JTextField passsignup;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JLabel statusbtn;
    // End of variables declaration//GEN-END:variables
}
